FROM dangelomagallanes/ubbase

USER root
RUN apt update && apt install -yq --no-install-recommends \
   nginx 

RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html


#INSTALO NGIX/APACHE --> usuario www-data
# el propietario de /var/www/html debe ser  www-data

RUN mkdir -p /var/log/nginx
EXPOSE 80

RUN mkdir -p /root/admin/sweb/nginx
COPY ./dockerfiles/sweb/nginx /root/admin/sweb/nginx 
RUN chdmod +x /root/admin/sweb/nginx/admin/start.sh
RUN mv /var/www/html/index.nginx-debian.html /var/www/html/index.html
WORKDIR /root/admin/sweb/nginx 
ENTRYPOINT [ "start.sh" ]